### ISSUE TITLE
这里代码会不会死循环 

### ISSUE THREAD

**Issue by StoneHao** [Morgan279/miniDB#1]
![image](https://user-images.githubusercontent.com/41334723/227499232-df218915-409c-4813-b48b-32b9d28ae648.png)

**Comment by Morgan279** [comment]
你好，经排查发现确实存在该问题，应该是之前写的时候笔误了，感谢指正。

现在已经在[Commit bdaba1](https://github.com/Morgan279/miniDB/commit/bdaba1b1cb823462ae8aa079a238c217d8b0571d)中进行了修复并增加了相应测试用例。
